### ISSUE TITLE
ox_target

### ISSUE THREAD

**Issue by Bobbbe** [esx-framework/esx_banking#12]
Hi, it's possible to add a option in config.lua to open menu and the option with ox_target and disable the "E" key at the same time of course?  [activate ox_target = true or false]
thx :)

**Comment by TheFantomas** [comment]
Hello,

In the current state, this script will not be added to our scripts, or rather, we will not add any third-party scripts to our scripts.

Still, thank you for this suggestion and for trying to improve our framework with your suggestion.

Sincerely, respectfully
Management/Leadert of ESX Legacy Team
**Fantík**
