### ISSUE TITLE
[BUG] Transfer

### ISSUE THREAD

**Issue by kangoka** [esx-framework/esx_banking#26]
Hi, recently I noticed the line below never handles if the transfer amount is more than bank balance.
https://github.com/esx-framework/esx_banking/blob/0c4de46d25c4064008bf2303db19c321a4bc2808/server/main.lua#L70-L77
Yes, the transfer will not go through. But, it still logging into the database [proof](https://prnt.sc/XBFtiJn5_TZ8). For now, I just type return after line 77 and it stops logging.

**Steps to reproduce**
1. Enter the **Amount** just slightly higher than bank balance
2. Enter the **Player ID** whether it's on the server or not
3. Click on the **Transfer** button

**Version**
es_extended: 1.9.4
esx_banking: 1.0

**Comment by Gellipapa** [comment]
@kangoka Hi! https://github.com/esx-framework/esx_banking/pull/28 merge will solve your problem, thanks for reporting the issue.
