### ISSUE TITLE
no vpn

### ISSUE THREAD

**Issue by ZZG994521** [esx-framework/esx_banking#27]
An error occurred in the F8 console：[    776250] [b2699_GTAProce]        CrBrowserMain/ Uncaught ReferenceError: $ is not defined (@esx_banking/html/scripts/app.js:675)

In mainland China, the player does not turn on the vpn and tries to press E to open the bank interface, but it gets stuck, only the mouse, and no bank interface appears.

**Comment by Gellipapa** [comment]
@ZZG994521 Hi! Thank you for report this issue. I think CDN don't support your region. I can't testing this please try change cdn link in html. JQuery version 3.6.0.

**Comment by Gellipapa** [comment]
#28 merge will solve your problem, thanks for reporting the issue.
Info: China blocking Jquery CDN link, i added jquery file, now working perfectly.
