### ISSUE TITLE
attempt to call a nil value (global 'TranslateCap')

### ISSUE THREAD

**Issue by MauriceHandwerker** [esx-framework/esx_banking#31]
Hi I have this error here:
![image](https://github.com/esx-framework/esx_banking/assets/66009198/4e58b353-b6f6-4189-b835-0dbbd4b4d6b4)
Ive tried reserching what ``TranslateCap`` or ``TextUi`` is but I dont find anything in the ESX Documantation.

**Comment by Cyzxin** [comment]
likely your esx is not updated. i would suggest updating to 1.10.1

**Comment by Gellipapa** [comment]
@MauriceHandwerker Hi! You should download latest esx_core because you use old version and don't have these methods your core.
