### ISSUE TITLE
Show more history button crash

### ISSUE THREAD

**Issue by Jxncsi** [esx-framework/esx_banking#40]
When I press the 'Show more history' button, the banking panel crashes and doesn't hide.

**Comment by Jxncsi** [comment]
And I translated the money withdraw/deposit in the account history, when I withdraw/deposit the money it still writes as it should, but when I close and open the bank it writes in English.

**Comment by Gellipapa** [comment]
Hi! @Jxncsi Can you show me any error in client or server console?

**Comment by Jxncsi** [comment]
Hi! I don't see any error in client and server console.

**Comment by Jxncsi** [comment]
Hi @Gellipapa the button is working!

**Comment by Jxncsi** [comment]
![image](https://github.com/esx-framework/esx_banking/assets/158039813/cb5fe27d-b6e9-4ffc-be07-34f24cfb612c)
![image](https://github.com/esx-framework/esx_banking/assets/158039813/eda00739-86c3-4c56-9280-fce9e208abae)
I deposit/withdraw money, the transaction history it hungary but when I open the panel, It always english.

**Comment by Gellipapa** [comment]
@Jxncsi Hi! I fixed your problem, please download latest version and re-test. Thanks.
